name: Build
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  main:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "8.10.7"
          - "9.0.2"
          - "9.2.7"
          - "9.4.5"
          - "9.6.1"
        include:
        - os: macOS-latest
          ghc: "9.6.1"
        - os: windows-latest
          ghc: "9.6.1"
    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2.0.2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-update: true
    - uses: actions/cache@v2
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Cabal version
      run: |
        cabal --version
    - name: Build & Test default
      run: |
        cabal sdist --ignore-project --output-directory .
        cabal get atomic-counter-*.tar.gz -d default
        cd default/atomic-counter-*/
        cabal build --project-file cabal.project.ci all
        cabal test --project-file cabal.project.ci --test-show-details=direct all
        cabal bench --project-file cabal.project.ci --benchmark-options='--stdev 100 --timeout 100' all
    - name: Haddock
      run: |
        cd default/atomic-counter-*/
        cabal haddock all

    - name: Build & Test no cmm
      run: |
        cabal sdist --ignore-project --output-directory .
        cabal get atomic-counter-*.tar.gz -d no-cmm
        cd no-cmm/atomic-counter-*/
        cabal build --project-file cabal.project.ci --constraint "atomic-counter +no-cmm" all
        cabal test --project-file cabal.project.ci --constraint "atomic-counter +no-cmm" --test-show-details=direct all
        cabal bench --project-file cabal.project.ci --constraint "atomic-counter +no-cmm" --benchmark-options='--stdev 100 --timeout 100' all

