name: Build
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  main:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "8.10.7"
          - "9.0.2"
          - "9.2.5"
          - "9.4.4"
          - "9.6.1"
        include:
        - os: macOS-latest
          ghc: "9.6.1"
        - os: windows-latest
          ghc: "9.6.1"
    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2.0.2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
    - uses: actions/cache@v2
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Cabal version
      run: |
        cabal --version
    - name: Build & Test
      run: |
        cabal sdist --ignore-project --output-directory .
        cabal get atomic-counter-*.tar.gz
        cd atomic-counter-*/
        cabal build all --enable-tests
        cabal test --enable-tests --test-show-details=direct all
        cabal bench --enable-benchmarks --benchmark-options='--stdev 100 --timeout 100' all
    - name: Haddock
      run: |
        cd atomic-counter-*/
        cabal haddock all
