name: Build
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  main:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "8.10.7"
          - "9.0.2"
          - "9.2.8"
          - "9.4.5"
          - "9.6.2"
        include:
        - os: macOS-latest
          ghc: "9.6.2"
        - os: windows-latest
          ghc: "9.6.2"
    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"
        cabal-update: true
    - uses: actions/cache@v2
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Cabal version
      run: |
        cabal --version
    - name: Build & Test default
      run: |
        cabal sdist --ignore-project --output-directory .
        cabal get atomic-counter-*.tar.gz -d default
        cd default/atomic-counter-*/
        cabal build --project-file cabal.project.ci all
        cabal test --project-file cabal.project.ci --test-show-details=direct all
        cabal bench --project-file cabal.project.ci --benchmark-options='--stdev 100 --timeout 100' all
    - name: Haddock
      run: |
        cd default/atomic-counter-*/
        cabal haddock all
    - name: Cabal check
      run: |
        cd default/atomic-counter-*/
        cabal check

    - name: Build & Test no cmm
      run: |
        cabal sdist --ignore-project --output-directory .
        cabal get atomic-counter-*.tar.gz -d no-cmm
        cd no-cmm/atomic-counter-*/
        cabal build --project-file cabal.project.ci --constraint "atomic-counter +no-cmm" all
        cabal test --project-file cabal.project.ci --constraint "atomic-counter +no-cmm" --test-show-details=direct all
        cabal bench --project-file cabal.project.ci --constraint "atomic-counter +no-cmm" --benchmark-options='--stdev 100 --timeout 100' all

  i386:
    runs-on: ubuntu-latest
    container:
      image: i386/ubuntu:bionic

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "9.2"
          - "9.4"
          - "9.6"

    steps:
    - name: Install
      run: |
        apt-get update -y
        apt-get install -y autoconf build-essential zlib1g-dev libgmp-dev curl libncurses5 libtinfo5 libncurses5-dev libtinfo-dev

        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_MINIMAL=1 sh

        source ~/.ghcup/env
        ghcup install ghc --set ${{ matrix.ghc }}
        ghcup install cabal latest

    - uses: actions/checkout@v1

    - name: Cabal version
      run: |
        source ~/.ghcup/env
        cabal --version
    - name: Build & Test default
      run: |
        source ~/.ghcup/env
        cabal update

        cabal sdist --ignore-project --output-directory .
        cabal get atomic-counter-*.tar.gz -d default
        cd default/atomic-counter-*/
        cabal build --project-file cabal.project.ci all
        cabal test --project-file cabal.project.ci --test-show-details=direct all
        cabal bench --project-file cabal.project.ci --benchmark-options='--stdev 100 --timeout 100' all

